artifact_root: "artifacts/"

data-ingestion:
  outdir: &data_ingestion "data/"
  raw:
    source: kaggle
    type: competition
    name: jigsaw-agile-community-rules

data-validation:
  outdir: "data/"
  statistics: false

data-transformation:
  outdir: "data/"
  indir: *data_ingestion
  splitter: splitter
  urlparse: true
  wash: false
  zero: false
  triplet: false
  #   ntriplets: 1
  #   nsamples: 5
    
  pairwise: false

model-training:
  outdir: "models/"
  indir: *data_ingestion
  fold: 1
  engine: "classifier"
  few-shot: true
