artifact-root: "artifact"
seed: 2345
schema-path: "schemas"
debug: true

data:
  sources:
    competition:
      source: local
      type: dir
      uri: "/kaggle/input/jigsaw-agile-community-rules"

  validation:
    statistics: false
    data-drift: 
      n_splits: 20
      n_iterations: 100
      dimension: 500
    report-name: "report"

  zero-shot: true


fold: -1
n-epochs: 1
valid-batch-size: 8
inference-batch-size: 8
learning-rate: 2e-4
warmup-ratio: 0.1
weight-decay: 0.01
max-grad-norm: 1.0
logging-steps: 10
gradient-checkpointing: true
dataloader-pin-memory: true
scheduler-type: "cosine"
save-strategy: "no"
max-length: 256
optimizer: "paged_adamw_8bit"
augmentations:
  fraction: 1.0
  n-resamples: 1
  include-original: false
  weight: 1.0
  augments: 
    - [url_to_semantics, 1.0]

models:
    deberta1:
        type: "text-classification"
        model: "/kaggle/input/huggingfacedebertav3variants/deberta-v3-base"
        augmentations: true
        train-batch-size: 32
        n-epochs: 0.1
        learning-rate: 2e-5
        gradient-accumulation-steps: 1
        padding: 'longest'
        optimizer: "adamw_torch_fused"

    deberta2:
        type: "text-classification"
        model: "/kaggle/input/huggingfacedebertav3variants/deberta-v3-base"
        augmentations: true
        train-batch-size: 32
        n-epochs: 0.1
        learning-rate: 2e-5
        gradient-accumulation-steps: 1
        padding: 'longest'
        optimizer: "adamw_torch_fused"