artifact_root: "artifacts/"

data-ingestion:
  outdir: &data_ingestion "data/"
  raw:
    source: kaggle
    type: competition
    name: jigsaw-agile-community-rules

data-validation:
  outdir: "data/"
  statistics: false

data-transformation:
  outdir: "data/"
  indir: *data_ingestion
  splitter: splitter
  wash: true
  zero: true
  triplet:
    ntriplets: 1
    nsamples: 5
    
  pairwise: false
