artifact_root: "artifacts/"

data-ingestion: 
  outdir: "data/"
  raw:
    source: kaggle
    type: competition
    name: jigsaw-agile-community-rules

data-validation:
  outdir: "data/validation"
  statistics: false